# Generated by Django 4.2 on 2023-04-22 11:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("student", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Choice",
            new_name="Student",
        ),
    ]
